### ISSUE TITLE
L510E

### ISSUE THREAD

**Issue by parryg** [apatsufas/homebridge-tapo-p100#1]
Hi,

I note you've written it should be easy to add support for the L510E bulb. I have one of these and would be happy to test if you update the package to support.

**Comment by apatsufas** [comment]
Hello,

can't promise anything, but I will try to find the time.

Could you for now check if the plugin can connect with the lightbulb? And does, maybe, the on/off functionality work?

**Comment by apatsufas** [comment]
@parryg I did some progress.

Could you check the beta branch and let me know if you have any issues?

You can install it with the following command:

npm install git://github.com/apatsufas/homebridge-tapo-p100git#beta -g

For the Lightbulb to be recognised as such you will have to update the config and add the "type" property with value "light". I have also updated the readme in the brach to include this option. 

Let me know if you have any questions and how it is working.

**Comment by parryg** [comment]
Hi,

The command doesn't work for me:

npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/apatsufas/homebridge-tapo-p100git.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by apatsufas** [comment]
Sorry my bad. Try:
npm install -g https://github.com/apatsufas/homebridge-tapo-p100.git#beta -g

**Comment by parryg** [comment]
Thank you. I have installed at configured, however I get stuck in a loop and this is repeated in the log:

rror: The requested platform 'TapoP100' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by apatsufas** [comment]
Can you send me your config?

**Comment by apatsufas** [comment]
I think I found a better way to share with you the beta.
Try uninstalling the plugin and then use the following command to install it:
npm install -g homebridge-tapo@1.1.1-beta.0

Sorry for the inconvenience, I'm just getting the hang of this :)

**Comment by parryg** [comment]
Works perfectly now, bulb turns on and off and I can control the brightness as well, thank you!
