### ISSUE TITLE
Any help for this problem: 152 Error & 333 Error?

### ISSUE THREAD

**Issue by 49jpg** [apatsufas/homebridge-tapo-p100#13]
**Describe Your Problem:**
152 Error Code: 0, Success
333 Error Code: -1501, Invalid Request or Credentials

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.4.7 
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.17.1
* **NPM Version**: v7.17.0
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by Wise-Fruit** [comment]
got the same problem.

**Comment by Wise-Fruit** [comment]
got the same issue:

17/09/2021, 23:15:22] [Tapo Smart Platform] Initializing TapoP100 platform...
[17/09/2021, 23:15:22] [Tapo Smart Platform] Loading accessory from cache: 192.168.X.XXX
[17/09/2021, 23:15:22] [Tapo Smart Platform] Restoring existing accessory from cache: 192.168.X.XXX
[17/09/2021, 23:15:22] [Tapo Smart Platform] Adding new accessory: undefined
[17/09/2021, 23:15:23] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:400:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at TapoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:112:29)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:40:12)
    at HomebridgeAPI.emit (events.js:400:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
[17/09/2021, 23:15:23] Got SIGTERM, shutting down Homebridge...

**Comment by Wise-Fruit** [comment]
23/09/2021, 17:58:28] Homebridge v1.3.4 (Homebridge C7C0) is running on port 51752.
[23/09/2021, 17:58:28] [Tapo Smart Platform] 152 Error Code: 0, Success
[23/09/2021, 17:58:28] [Tapo Smart Platform] 152 Error Code: 0, Success
[23/09/2021, 17:58:28] [Tapo Smart Platform] 333 Error Code: -1501, Invalid Request or Credentials
[23/09/2021, 17:58:28] [Tapo Smart Platform] Get Device Info failed

**Comment by apatsufas** [comment]
From the error it seems that the problem is with the credentials provided. From what I understand the Tapo platform has a lot of quirks with credentials. Check out https://github.com/fishbigger/TapoP100/issues/1 for some more issues that have been documented

**Comment by apatsufas** [comment]
The L530E is supported. I actually have one running in my home. Please read through the issues I have linked to for the python / home assistant plugin from which my plugin derived. You will also need to reset the plug after changing the password.

The following should work:

1. Password max 8 charactes
2. No special characters in the password
3. Reset the plug after changing password

These steps have worked for me.

**Comment by Wise-Fruit** [comment]
I am sorry, this is not a solution. 
As seen in many other comments, it simply won't work.
Even after changing everything and reseting it 10 times.

**Comment by DenDan88** [comment]
I tried everything on this page nothing helped.

but maybe this one helps. Dont use you User Login on the Plugin, but your email adress with the one you created the account.
Password 8 charactere long. Just letters and numbers.

now it works on my side 😁

thanks a lot for the Plugin 👍

**Comment by AFJAIGHAJF** [comment]
In my case, it worked as I created a new account and put my Email adress as username. 
Like @DenDan88 wrote. 
Thanks a lot for the Plugin
