### ISSUE TITLE
Child bridge process ended

### ISSUE THREAD

**Issue by katapablo** [apatsufas/homebridge-tapo-p100#45]
The process of stasrting the child bridge are restarting and can finally start.
always the same log, reteat again and again.

If i cancel using child bridge give me other error and cant start the homebridge service
<
Raspbian GNU/Linux Buster (10)

v18.17.1
pi/var/lib/homebridge
/var/lib/homebridge/config.json

[31/08/2023, 14:53:42] [Tapo Smart Platform] Restarting Process...
[31/08/2023, 14:53:43] [Tapo Smart Platform] Launched child bridge with PID 27762
[31/08/2023, 14:53:46] Registering platform 'homebridge-tapo.TapoP100'
[31/08/2023, 14:53:46] [Tapo Smart Platform] Loaded homebridge-tapo v1.4.17 child bridge successfully
[31/08/2023, 14:53:46] [Tapo Smart Platform] Adding new accessory: undefined
[31/08/2023, 14:53:46] Homebridge v1.6.1 (HAP v0.11.1) (Tapo Smart Platform) is running on port 41308.
AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:71:9)
    at TapoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:159:25)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:59:12)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:189:14)
[31/08/2023, 14:53:46] [Tapo Smart Platform] Child bridge process ended
[31/08/2023, 14:53:46] [Tapo Smart Platform] Process Ended. Code: 1, Signal: null
[31/08/2023, 14:53:53] [Tapo Smart Platform] Restarting Process...
[31/08/2023, 14:53:54] [Tapo Smart Platform] Launched child bridge with PID 27773
[31/08/2023, 14:53:57] Registering platform 'homebridge-tapo.TapoP100'
[31/08/2023, 14:53:57] [Tapo Smart Platform] Loaded homebridge-tapo v1.4.17 child bridge successfully
[31/08/2023, 14:53:57] [Tapo Smart Platform] Adding new accessory: undefined
[31/08/2023, 14:53:57] Homebridge v1.6.1 (HAP v0.11.1) (Tapo Smart Platform) is running on port 41308.
AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:71:9)
    at TapoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:159:25)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:59:12)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:189:14)
[31/08/2023, 14:53:57] [Tapo Smart Platform] Child bridge process ended
[31/08/2023, 14:53:57] [Tapo Smart Platform] Process Ended. Code: 1, Signal: null
[31/08/2023, 14:54:04] [Tapo Smart Platform] Restarting Process...
[31/08/2023, 14:54:06] [Tapo Smart Platform] Launched child bridge with PID 27784
[31/08/2023, 14:54:08] Registering platform 'homebridge-tapo.TapoP100'
[31/08/2023, 14:54:08] [Tapo Smart Platform] Loaded homebridge-tapo v1.4.17 child bridge successfully
[31/08/2023, 14:54:08] [Tapo Smart Platform] Adding new accessory: undefined
[31/08/2023, 14:54:09] Homebridge v1.6.1 (HAP v0.11.1) (Tapo Smart Platform) is running on port 41308.
AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:491:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:71:9)
    at TapoPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:159:25)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-tapo/src/platform.ts:59:12)
    at HomebridgeAPI.emit (node:events:514:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:189:14)
[31/08/2023, 14:54:09] [Tapo Smart Platform] Child bridge process ended
[31/08/2023, 14:54:09] [Tapo Smart Platform] Process Ended. Code: 1, Signal: null

**Comment by apatsufas** [comment]
@katapablo Could you please share your configuration ?

**Comment by katapablo** [comment]
Hello dear Andreas, what configuration you want?
Plugin config or homebridge config?

Regards, and thanks you so much for your email

**Comment by katapablo** [comment]
Now the problem of child bridge ended is solved, the problem is other. See attachment Enviado desde mi iPhoneEl 19 oct 2023, a las 12:23, Andreas Zimnas ***@***.***> escribió:﻿
@katapablo the plugin config.
