### ISSUE TITLE
Les L530E ne sont pas reconnues

### ISSUE THREAD

**Issue by polo12113** [apatsufas/homebridge-tapo-p100#5]
les L530E ne sont pas reconnu correctement, impossible de choisir des couleur, on ne peut que utiliser la puissance de luminosité

**Comment by apatsufas** [comment]
Hello, yes that is correct the current version does not support color temperature and saturation options for the L530E.
But I have a Beta Version which you could try.

Use npm install -g homebridge-tapo@1.2.2-beta.0 to install it.

Let me know how it works for you

**Comment by polo12113** [comment]
Super Merci ! J'ai bien les commandes pour les couleurs qui apparaissent
mais elle ne sont pas active apparemment

Le mer. 17 mars 2021 à 07:28, Andreas Zimnas ***@***.***> a
écrit :

**Comment by apatsufas** [comment]
It doesn't change the color temperature nor the saturation ? Do you have any error messages in the Homebridge log?

**Comment by polo12113** [comment]
No, it doesn't.

Le mer. 17 mars 2021 à 10:32, Andreas Zimnas ***@***.***> a
écrit :

**Comment by apatsufas** [comment]
Could you sent me your config and the homebridge log ?

**Comment by polo12113** [comment]
Sure, here it is.

Le mer. 17 mars 2021 à 15:49, Andreas Zimnas ***@***.***> a
écrit :

**Comment by apatsufas** [comment]
> Sure, here it is. Le mer. 17 mars 2021 à 15:49, Andreas Zimnas ***@***.***> a écrit :
> […](#)

Sorry but I don't see them.  Can you try sending them again?

**Comment by apatsufas** [comment]
> Le mer. 17 mars 2021 à 17:48, Andreas Zimnas ***@***.***> a écrit :
> […](#)

If you are replying through email, the attachments are probably not coming through.

**Comment by polo12113** [comment]
`
    "bridge": {
        "name": "Homebridge",
        "username": "9E:12:CE:92:DB:74",
        "port": 51826,
        "pin": "591-32-067"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 80,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "pm2 restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": false,
            "log": {
                "method": "custom",
                "command": "pm2 logs --raw --out --lines 80 homebridge"
            },
            "platform": "config"
        },
        {
            "name": "Tapo Smart Platform",
            "username": "castaniepaul@gmail.com",
            "password": "yHa20121406",
            "devices": [
                {
                    "name": "Tapo L530E",
                    "host": "192.168.0.15",
                    "type": "Colorlight"
                }
            ],
            "platform": "TapoP100",
            "_bridge": {
                "username": "0E:1C:5D:1C:7C:75",
                "port": 36639
            }
        }
    ],
    "accessories": []
}`

**Comment by polo12113** [comment]
"bridge": {
        "name": "Homebridge",
        "username": "9E:12:CE:92:DB:74",
        "port": 51826,
        "pin": "591-32-067"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 80,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "pm2 restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": false,
            "log": {
                "method": "custom",
                "command": "pm2 logs --raw --out --lines 80 homebridge"
            },
            "platform": "config"
        },
        {
            "name": "Tapo Smart Platform",
            "username": "castaniepaul@gmail.com",
            "password": "yHa20121406",
            "devices": [
                {
                    "name": "Tapo L530E",
                    "host": "192.168.0.15",
                    "type": "Colorlight"
                }
            ],
            "platform": "TapoP100",
            "_bridge": {
                "username": "0E:1C:5D:1C:7C:75",
                "port": 36639
            }
        }
    ],
    "accessories": []
}

**Comment by polo12113** [comment]
Starting to advertise 'Homebridge 18D8' using bonjour-hap backend!
[3/17/2021, 6:57:50 PM] Homebridge v1.3.4 (Homebridge) is running on port 51826.
Initializing HAP-NodeJS v0.9.4...
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Launched child bridge with PID 10661
[3/17/2021, 6:57:51 PM] Registering platform 'homebridge-tapo.TapoP100'
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Loaded homebridge-tapo v1.2.2-beta.0 child bridge successfully
[3/17/2021, 6:57:51 PM] Loaded 1 cached accessories from cachedAccessories.0E1C5D1C7C75.
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] config.json: {"name":"Tapo Smart Platform","username":"castaniepaul@gmail.com","password":"yHa20121406","devices":[{"name":"Tapo L530E","host":"192.168.0.15","type":"Colorlight"}],"platform":"TapoP100"}
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] config: {"name":"Tapo Smart Platform","username":"castaniepaul@gmail.com","password":"yHa20121406","waitTimeUpdate":100,"defaultSendOptions":{"timeout":15000},"discoveryOptions":{"discoveryInterval":10000,"deviceOptions":{"defaultSendOptions":{"timeout":15000}},"devices":[{"name":"Tapo L530E","host":"192.168.0.15","type":"Colorlight"}]}}
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Finished initializing platform: Tapo Smart Platform
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Loading accessory from cache: 192.168.0.15
Preparing Advertiser for 'Tapo Smart Platform 152E' using bonjour-hap backend!
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Executed didFinishLaunching callback
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Restoring existing accessory from cache: 192.168.0.15
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Start adding accessory: 192.168.0.15
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Constructing P100 on host: 192.168.0.15
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Constructing L510E on host: 192.168.0.15
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Constructing L530 on host: 192.168.0.15
[3/17/2021, 6:57:51 PM] [Tapo Smart Platform] Handshake P100 on host: 192.168.0.15
Starting to advertise 'Tapo Smart Platform 152E' using bonjour-hap backend!
[3/17/2021, 6:57:51 PM] Homebridge v1.3.4 (Tapo Smart Platform) is running on port 36639.

[3/17/2021, 6:58:23 PM] [Tapo Smart Platform] Received Handshake P100 on host response: 192.168.0.15
[3/17/2021, 6:58:24 PM] [Tapo Smart Platform] Get Characteristic On -> false
[3/17/2021, 6:58:24 PM] [Tapo Smart Platform] Get Characteristic Color Temperature -> 140
[3/17/2021, 6:58:24 PM] [Tapo Smart Platform] Get Characteristic Brightness -> 44
[3/17/2021, 6:58:24 PM] [Tapo Smart Platform] Get Characteristic Hue -> undefined
[3/17/2021, 6:58:24 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/17/2021, 6:58:24 PM] [homebridge-tapo] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Hue.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:196:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/17/2021, 6:58:24 PM] [Tapo Smart Platform] Get Characteristic Saturation -> undefined
[3/17/2021, 6:58:24 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/17/2021, 6:58:24 PM] [homebridge-tapo] Error: 
    at Saturation.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Saturation.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:228:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/17/2021, 6:58:28 PM] [Tapo Smart Platform] Set Characteristic On -> true
[3/17/2021, 6:58:30 PM] [Tapo Smart Platform] Set Characteristic On -> false
[3/17/2021, 6:58:32 PM] [Tapo Smart Platform] Set Characteristic On -> true
[3/17/2021, 6:58:35 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/17/2021, 6:58:35 PM] [Tapo Smart Platform] Set Characteristic Hue -> 0
[3/17/2021, 6:58:41 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 36
[3/17/2021, 6:58:41 PM] [Tapo Smart Platform] Set Characteristic Hue -> 177
[3/17/2021, 6:58:43 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/17/2021, 6:58:43 PM] [Tapo Smart Platform] Set Characteristic Hue -> 105
[3/17/2021, 6:58:44 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/17/2021, 6:58:44 PM] [Tapo Smart Platform] Set Characteristic Hue -> 295
[3/17/2021, 6:58:45 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 18
[3/17/2021, 6:58:45 PM] [Tapo Smart Platform] Set Characteristic Hue -> 41
[3/17/2021, 6:58:46 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 140
[3/17/2021, 6:58:48 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 36
[3/17/2021, 6:58:48 PM] [Tapo Smart Platform] Set Characteristic Hue -> 177
[3/17/2021, 6:58:48 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/17/2021, 6:58:48 PM] [Tapo Smart Platform] Set Characteristic Hue -> 0
[3/17/2021, 6:58:52 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/17/2021, 6:58:52 PM] [Tapo Smart Platform] Set Characteristic Hue -> 295
[3/17/2021, 6:58:53 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 18
[3/17/2021, 6:58:53 PM] [Tapo Smart Platform] Set Characteristic Hue -> 41

**Comment by polo12113** [comment]
les commandes que j'effectue s'affiche mais rien ne se passe

**Comment by apatsufas** [comment]
Thanks for the info. I'll take a look and see if I can think of something.

**Comment by polo12113** [comment]
Thanks!

Le mer. 17 mars 2021 à 21:07, Andreas Zimnas ***@***.***> a
écrit :

**Comment by apatsufas** [comment]
Could you try a new beta version I just published? The version is 1.3.1-beta.0.

**Comment by polo12113** [comment]
Ça marche je le ferais plus tard !

Le jeu. 18 mars 2021 à 07:44, Andreas Zimnas ***@***.***> a
écrit :

**Comment by apatsufas** [comment]
Let me know how it goes

**Comment by polo12113** [comment]
Will do, thanks!

Le jeu. 18 mars 2021 à 10:21, Andreas Zimnas ***@***.***> a
écrit :

**Comment by polo12113** [comment]
bonjour, ça ne marche toujours pas


Le jeu. 18 mars 2021 à 11:09, Paul Castanie ***@***.***> a
écrit :

**Comment by polo12113** [comment]
rien ne se passe, je ne peux modifier que la température de la lampe mais
pas de RGB

Le dim. 21 mars 2021 à 00:33, Paul Castanie ***@***.***> a
écrit :

**Comment by apatsufas** [comment]
Could you once more sent me the log?
Sorry but I don't have the specific device, which makes it difficult to understand why it is not working.

**Comment by apatsufas** [comment]
Also could you update to Beta 1.3.4-beta.0 and sent me the log for that? I have added more logging in this version which may help identifying the issue easier.

**Comment by polo12113** [comment]
je suis sur truenas core


Le dim. 21 mars 2021 à 08:32, Andreas Zimnas ***@***.***> a
écrit :

**Comment by polo12113** [comment]
Loading logs using "custom" method...
CMD: pm2 logs --raw --out --lines 80 homebridge

[TAILING] Tailing last 80 lines for [homebridge] process (change the value with --lines option)
/root/.pm2/logs/homebridge-out.log last 80 lines:
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Color Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Hue' was slow to respond! See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Saturation' was slow to respond! See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [Tapo Smart Platform] Get Characteristic On -> true
[3/21/2021, 3:04:11 PM] [Tapo Smart Platform] Get Characteristic Brightness -> 57
[3/21/2021, 3:04:11 PM] [Tapo Smart Platform] Get Characteristic Color Temperature -> 257
[3/21/2021, 3:04:11 PM] [Tapo Smart Platform] Get Characteristic Hue -> undefined
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [homebridge-tapo] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Hue.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:199:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/21/2021, 3:04:11 PM] [Tapo Smart Platform] Get Characteristic Saturation -> undefined
[3/21/2021, 3:04:11 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:11 PM] [homebridge-tapo] Error: 
    at Saturation.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Saturation.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:232:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/21/2021, 3:04:17 PM] [Tapo Smart Platform] Get Characteristic Saturation -> undefined
[3/21/2021, 3:04:17 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:17 PM] [homebridge-tapo] Error: 
    at Saturation.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Saturation.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:232:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/21/2021, 3:04:17 PM] [Tapo Smart Platform] Get Characteristic On -> true
[3/21/2021, 3:04:17 PM] [Tapo Smart Platform] Get Characteristic Brightness -> 57
[3/21/2021, 3:04:17 PM] [Tapo Smart Platform] Get Characteristic Color Temperature -> 257
[3/21/2021, 3:04:17 PM] [Tapo Smart Platform] Get Characteristic Hue -> undefined
[3/21/2021, 3:04:17 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:17 PM] [homebridge-tapo] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Hue.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:199:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/21/2021, 3:04:19 PM] [Tapo Smart Platform] Get Characteristic Saturation -> undefined
[3/21/2021, 3:04:19 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:19 PM] [homebridge-tapo] Error: 
    at Saturation.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Saturation.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:232:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/21/2021, 3:04:19 PM] [Tapo Smart Platform] Get Characteristic Hue -> undefined
[3/21/2021, 3:04:19 PM] [homebridge-tapo] This plugin generated a warning from the characteristic 'Hue': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[3/21/2021, 3:04:19 PM] [homebridge-tapo] Error: 
    at Hue.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Hue.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /usr/local/lib/node_modules/homebridge-tapo/src/platformL530Accessory.ts:199:7
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
[3/21/2021, 3:04:19 PM] [Tapo Smart Platform] Get Characteristic Color Temperature -> 257
[3/21/2021, 3:04:20 PM] [Tapo Smart Platform] Get Characteristic Brightness -> 57
[3/21/2021, 3:04:20 PM] [Tapo Smart Platform] Get Characteristic On -> true
[3/21/2021, 3:04:23 PM] [Tapo Smart Platform] Set Color Temp Response [object Object]
[3/21/2021, 3:04:23 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 366
[3/21/2021, 3:04:25 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 67
[3/21/2021, 3:04:25 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 3:04:25 PM] [Tapo Smart Platform] Set Characteristic Hue -> 30
[3/21/2021, 3:04:25 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 3:04:26 PM] [Tapo Smart Platform] Set Color Temp Response [object Object]
[3/21/2021, 3:04:26 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 257
[3/21/2021, 3:04:29 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 97
[3/21/2021, 3:04:29 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 3:04:29 PM] [Tapo Smart Platform] Set Characteristic Hue -> 355
[3/21/2021, 3:04:29 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined

**Comment by polo12113** [comment]
This is the log

**Comment by apatsufas** [comment]
Great. Thank you. That is helpful. It seems the Device doesn't return the current hue and saturation values or doesn't return it as I would expect it from what I have seen so far. 
So please when you find time update to 1.3.5-beta.0 and send me the log once more.

**Comment by polo12113** [comment]
ça ne fonctionne toujours pas 
je vous envoie les log

**Comment by polo12113** [comment]
Loading logs using "custom" method...
CMD: pm2 logs --raw --out --lines 80 homebridge

[TAILING] Tailing last 80 lines for [homebridge] process (change the value with --lines option)
/root/.pm2/logs/homebridge-out.log last 80 lines:
[3/21/2021, 8:26:29 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:29 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 257
[3/21/2021, 8:26:32 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 67
[3/21/2021, 8:26:32 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:32 PM] [Tapo Smart Platform] Set Characteristic Hue -> 30
[3/21/2021, 8:26:32 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] Set Characteristic Hue -> 241
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 5
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] Set Characteristic Hue -> 251
[3/21/2021, 8:26:34 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:35 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:35 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 366
[3/21/2021, 8:26:37 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:37 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 257
[3/21/2021, 8:26:42 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:42 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 348
[3/21/2021, 8:26:48 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 38
[3/21/2021, 8:26:48 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:48 PM] [Tapo Smart Platform] Set Characteristic Hue -> 149
[3/21/2021, 8:26:48 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 98
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Hue -> 136
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Hue -> 124
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 85
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Hue -> 81
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 60
[3/21/2021, 8:26:49 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:26:50 PM] [Tapo Smart Platform] Set Characteristic Hue -> 23
[3/21/2021, 8:26:50 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:26:52 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:52 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 469
[3/21/2021, 8:26:53 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:53 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 433
[3/21/2021, 8:26:53 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:53 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 166
[3/21/2021, 8:26:54 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:54 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 146
[3/21/2021, 8:26:54 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:54 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 144
[3/21/2021, 8:26:55 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:55 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 148
[3/21/2021, 8:26:55 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:55 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 149
[3/21/2021, 8:26:55 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:55 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 151
[3/21/2021, 8:26:57 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:57 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 173
[3/21/2021, 8:26:59 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:59 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 228
[3/21/2021, 8:26:59 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:26:59 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 236
[3/21/2021, 8:27:00 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:27:00 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 181
[3/21/2021, 8:27:05 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/21/2021, 8:27:05 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:27:05 PM] [Tapo Smart Platform] Set Characteristic Hue -> 241
[3/21/2021, 8:27:05 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:27:07 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:27:07 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 366
[3/21/2021, 8:27:07 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 68
[3/21/2021, 8:27:07 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:27:07 PM] [Tapo Smart Platform] Set Characteristic Hue -> 255
[3/21/2021, 8:27:07 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined
[3/21/2021, 8:27:09 PM] [Tapo Smart Platform] Set Color Temp Response  { error_code: 0 }
[3/21/2021, 8:27:09 PM] [Tapo Smart Platform] Set Characteristic Color Temperature -> 181
[3/21/2021, 8:27:10 PM] [Tapo Smart Platform] Set Characteristic Saturation -> 100
[3/21/2021, 8:27:10 PM] [Tapo Smart Platform] With Characteristic Hue -> undefined
[3/21/2021, 8:27:10 PM] [Tapo Smart Platform] Set Characteristic Hue -> 241
[3/21/2021, 8:27:10 PM] [Tapo Smart Platform] With Characteristic Saturation -> undefined

**Comment by apatsufas** [comment]
Yeah it won't work. I just added more logs to identify why it is not working. Could you sent we a little bit more of the log? Something where a Set is called? Maybe just after opening the Home app?

**Comment by apatsufas** [comment]
Fixed with 1.4.3
